package ./dist directory instead of the repo - oops :) (#189)
This should address at least the 
`Cannot find module 'angular-typesafe-reactive-forms-helper' or its corresponding type declarations.ts(2307)`
mentioned in issue - https://github.com/rpbeukes/angular-typesafe-reactive-forms-helper/issues/184